name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main 
    paths-ignore:
      - 'README.md'  # Exclude README file from triggering the workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your actual dependencies
        
    - name: Run tests
      run: |
        python -m pytest  # Replace with your test command
