# Define the name of the GitHub Actions workflow as "Continuous Integration"
name: Continuous Integration

# Define the events that trigger the workflow
on:
  pull_request:  # Trigger on pull requests
  push:  # Trigger on push events
    branches:
      - main  # Trigger only when pushing to the main branch
    paths-ignore:
      - 'README.md'  # Exclude README file from triggering the workflow

# Define the jobs to be executed in the workflow
jobs:
  # Define a job named "build"
  build:
    # Specify the operating system for the job using a matrix
    runs-on: ${{ matrix.os }}
    
    # Define a strategy for the matrix with different operating systems and Python versions
    strategy:
      matrix:
        os: [ubuntu-latest]  # Matrix for operating systems, can be [ubuntu-latest, windows-latest, macos-latest] 
        python-version: [3.8, 3.9]  # Matrix for Python versions

    # Define the steps to be executed in the job
    steps:
      # Step 1: Checkout the repository using the 'actions/checkout' action
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python using the 'actions/setup-python' action
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # Use the specified Python version
    
      # Step 3: Install dependencies using 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Replace with your actual dependencies

      # Step 4: Run tests using 'pytest'
      - name: Run tests
        run: |
          python -m pytest  # Replace with your test command
